-- Pinned FOREVER c6e899 API inventory. Declarative; no native calls or live data.
local _,A=...
local C={entries={}};A.UnitDataCatalog=C
C.entries[#C.entries+1]={["id"]="health",["api"]="UnitHealth",["family"]="unit",["args"]={"$unit",false},["outputs"]={{["key"]="health",["type"]="float",["label"]="health",["index"]=1,["nativeType"]="number",["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="healthMax",["api"]="UnitHealthMax",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="healthMax",["type"]="float",["label"]="health Max",["index"]=1,["nativeType"]="number",["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="healthMissing",["api"]="UnitHealthMissing",["family"]="unit",["args"]={"$unit",false},["outputs"]={{["key"]="healthMissing",["type"]="float",["label"]="health Missing",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="healthPercent",["api"]="UnitHealthPercent",["family"]="unit",["args"]={"$unit",false,"$nil"},["outputs"]={{["key"]="healthPercent",["type"]="float",["label"]="health Percent",["index"]=1,["nativeType"]="LuaCurveEvaluatedResult"}}}
C.entries[#C.entries+1]={["id"]="getIncomingHeals",["api"]="UnitGetIncomingHeals",["family"]="unit",["args"]={"$unit","$nil"},["outputs"]={{["key"]="getIncomingHeals",["type"]="float",["label"]="get Incoming Heals",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getTotalAbsorbs",["api"]="UnitGetTotalAbsorbs",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="getTotalAbsorbs",["type"]="float",["label"]="get Total Absorbs",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getTotalHealAbsorbs",["api"]="UnitGetTotalHealAbsorbs",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="getTotalHealAbsorbs",["type"]="float",["label"]="get Total Heal Absorbs",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getDetailedHealPrediction",["api"]="UnitGetDetailedHealPrediction",["family"]="unit",["args"]={"$unit","$nil","$calculator"},["outputs"]={{["key"]="healPrediction",["type"]="calculator",["label"]="Heal prediction",["index"]=1,["nativeType"]="UnitHealPredictionCalculator"}},["calculator"]=true}
C.entries[#C.entries+1]={["id"]="stagger",["api"]="UnitStagger",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="stagger",["type"]="float",["label"]="stagger",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="power",["api"]="UnitPower",["family"]="unit",["args"]={"$unit","$nil",false},["outputs"]={{["key"]="power",["type"]="float",["label"]="power",["index"]=1,["nativeType"]="number",["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="powerMax",["api"]="UnitPowerMax",["family"]="unit",["args"]={"$unit","$nil",false},["outputs"]={{["key"]="powerMax",["type"]="float",["label"]="power Max",["index"]=1,["nativeType"]="number",["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="powerMissing",["api"]="UnitPowerMissing",["family"]="unit",["args"]={"$unit","$nil",false},["outputs"]={{["key"]="powerMissing",["type"]="float",["label"]="power Missing",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="powerPercent",["api"]="UnitPowerPercent",["family"]="unit",["args"]={"$unit","$nil",false,"$nil"},["outputs"]={{["key"]="powerPercent",["type"]="float",["label"]="power Percent",["index"]=1,["nativeType"]="LuaCurveEvaluatedResult"}}}
C.entries[#C.entries+1]={["id"]="powerType",["api"]="UnitPowerType",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="powerType",["type"]="integer",["label"]="power Type",["index"]=1,["nativeType"]="PowerType"},{["key"]="powerToken",["type"]="string",["label"]="power Token",["index"]=2,["nativeType"]="string"},{["key"]="powerRed",["type"]="float",["label"]="power Red",["index"]=3,["nativeType"]="number"},{["key"]="powerGreen",["type"]="float",["label"]="power Green",["index"]=4,["nativeType"]="number"},{["key"]="powerBlue",["type"]="float",["label"]="power Blue",["index"]=5,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="powerDisplayMod",["api"]="UnitPowerDisplayMod",["family"]="unit",["args"]={"$power:Mana"},["outputs"]={{["key"]="powerDisplayMod",["type"]="float",["label"]="power Display Mod",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getUnitChargedPowerPoints",["api"]="GetUnitChargedPowerPoints",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="getUnitChargedPowerPoints",["type"]="data",["label"]="get Unit Charged Power Points",["index"]=1,["nativeType"]="table",["schema"]="numbers"}}}
C.entries[#C.entries+1]={["id"]="powerBarID",["api"]="UnitPowerBarID",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="powerBarID",["type"]="float",["label"]="power Bar I D",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getUnitPowerBarInfo",["api"]="GetUnitPowerBarInfo",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="getUnitPowerBarInfo",["type"]="data",["label"]="get Unit Power Bar Info",["index"]=1,["nativeType"]="UnitPowerBarInfo",["schema"]="powerBar"}}}
C.entries[#C.entries+1]={["id"]="getUnitPowerBarStrings",["api"]="GetUnitPowerBarStrings",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="getUnitPowerBarStrings_name",["type"]="string",["label"]="get Unit Power Bar Strings / name",["index"]=1,["nativeType"]="cstring"},{["key"]="getUnitPowerBarStrings_tooltip",["type"]="string",["label"]="get Unit Power Bar Strings / tooltip",["index"]=2,["nativeType"]="cstring"},{["key"]="getUnitPowerBarStrings_cost",["type"]="string",["label"]="get Unit Power Bar Strings / cost",["index"]=3,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="powerBarTimerInfo",["api"]="UnitPowerBarTimerInfo",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="powerBarTimerInfo_duration",["type"]="float",["label"]="power Bar Timer Info / duration",["index"]=1,["nativeType"]="number"},{["key"]="powerBarTimerInfo_expiration",["type"]="float",["label"]="power Bar Timer Info / expiration",["index"]=2,["nativeType"]="number"},{["key"]="powerBarTimerInfo_barID",["type"]="float",["label"]="power Bar Timer Info / bar I D",["index"]=3,["nativeType"]="number"},{["key"]="powerBarTimerInfo_auraID",["type"]="float",["label"]="power Bar Timer Info / aura I D",["index"]=4,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="name",["api"]="UnitName",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="name",["type"]="string",["label"]="name",["index"]=1,["nativeType"]="cstring"},{["key"]="realm",["type"]="string",["label"]="realm",["index"]=2,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="fullName",["api"]="UnitFullName",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="fullName",["type"]="string",["label"]="full Name",["index"]=1,["nativeType"]="cstring"},{["key"]="fullRealm",["type"]="string",["label"]="full Realm",["index"]=2,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="nameUnmodified",["api"]="UnitNameUnmodified",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="nameUnmodified_unitName",["type"]="string",["label"]="name Unmodified / unit Name",["index"]=1,["nativeType"]="cstring"},{["key"]="nameUnmodified_unitServer",["type"]="string",["label"]="name Unmodified / unit Server",["index"]=2,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="gUID",["api"]="UnitGUID",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="gUID",["type"]="string",["label"]="g U I D",["index"]=1,["nativeType"]="WOWGUID"}}}
C.entries[#C.entries+1]={["id"]="creatureID",["api"]="UnitCreatureID",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="creatureID",["type"]="float",["label"]="creature I D",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="creatureType",["api"]="UnitCreatureType",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="creatureType_name",["type"]="string",["label"]="creature Type / name",["index"]=1,["nativeType"]="cstring"},{["key"]="creatureType_id",["type"]="float",["label"]="creature Type / id",["index"]=2,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="creatureFamily",["api"]="UnitCreatureFamily",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="creatureFamily_name",["type"]="string",["label"]="creature Family / name",["index"]=1,["nativeType"]="cstring"},{["key"]="creatureFamily_id",["type"]="float",["label"]="creature Family / id",["index"]=2,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="class",["api"]="UnitClass",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="className",["type"]="string",["label"]="class Name",["index"]=1,["nativeType"]="cstring"},{["key"]="classToken",["type"]="string",["label"]="class Token",["index"]=2,["nativeType"]="cstring"},{["key"]="classID",["type"]="float",["label"]="class I D",["index"]=3,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="classBase",["api"]="UnitClassBase",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="classBase_classFilename",["type"]="string",["label"]="class Base / class Filename",["index"]=1,["nativeType"]="cstring"},{["key"]="classBase_classID",["type"]="float",["label"]="class Base / class I D",["index"]=2,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="race",["api"]="UnitRace",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="race_localizedRaceName",["type"]="string",["label"]="race / localized Race Name",["index"]=1,["nativeType"]="cstring"},{["key"]="race_englishRaceName",["type"]="string",["label"]="race / english Race Name",["index"]=2,["nativeType"]="cstring"},{["key"]="race_raceID",["type"]="float",["label"]="race / race I D",["index"]=3,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="sex",["api"]="UnitSex",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="sex",["type"]="float",["label"]="sex",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="sexBase",["api"]="UnitSexBase",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="sexBase",["type"]="integer",["label"]="sex Base",["index"]=1,["nativeType"]="UnitSex"}}}
C.entries[#C.entries+1]={["id"]="level",["api"]="UnitLevel",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="level",["type"]="float",["label"]="level",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="effectiveLevel",["api"]="UnitEffectiveLevel",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="effectiveLevel",["type"]="float",["label"]="effective Level",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="classification",["api"]="UnitClassification",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="classification",["type"]="string",["label"]="classification",["index"]=1,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="isBossMob",["api"]="UnitIsBossMob",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isBossMob",["type"]="boolean",["label"]="is Boss Mob",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isQuestBoss",["api"]="UnitIsQuestBoss",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isQuestBoss",["type"]="boolean",["label"]="is Quest Boss",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isTrivial",["api"]="UnitIsTrivial",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isTrivial",["type"]="boolean",["label"]="is Trivial",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isPlayer",["api"]="UnitIsPlayer",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="isPlayer",["type"]="boolean",["label"]="is Player",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isHumanPlayer",["api"]="UnitIsHumanPlayer",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="isHumanPlayer",["type"]="boolean",["label"]="is Human Player",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isNPCAsPlayer",["api"]="UnitIsNPCAsPlayer",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isNPCAsPlayer",["type"]="boolean",["label"]="is N P C As Player",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="playerControlled",["api"]="UnitPlayerControlled",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="playerControlled",["type"]="boolean",["label"]="player Controlled",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="ownerGUID",["api"]="UnitOwnerGUID",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="ownerGUID",["type"]="string",["label"]="owner G U I D",["index"]=1,["nativeType"]="WOWGUID"}}}
C.entries[#C.entries+1]={["id"]="isOtherPlayersPet",["api"]="UnitIsOtherPlayersPet",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isOtherPlayersPet",["type"]="boolean",["label"]="is Other Players Pet",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isOtherPlayersBattlePet",["api"]="UnitIsOtherPlayersBattlePet",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isOtherPlayersBattlePet",["type"]="boolean",["label"]="is Other Players Battle Pet",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="reaction",["api"]="UnitReaction",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="reaction",["type"]="integer",["label"]="reaction",["index"]=1,["nativeType"]="luaIndex"}}}
C.entries[#C.entries+1]={["id"]="isFriend",["api"]="UnitIsFriend",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="isFriend",["type"]="boolean",["label"]="is Friend",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isEnemy",["api"]="UnitIsEnemy",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="isEnemy",["type"]="boolean",["label"]="is Enemy",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="canAssist",["api"]="UnitCanAssist",["family"]="unit",["args"]={"$player","$unit",false,false},["outputs"]={{["key"]="canAssist",["type"]="boolean",["label"]="can Assist",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="canAttack",["api"]="UnitCanAttack",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="canAttack",["type"]="boolean",["label"]="can Attack",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="canCooperate",["api"]="UnitCanCooperate",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="canCooperate",["type"]="boolean",["label"]="can Cooperate",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isUnit",["api"]="UnitIsUnit",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="isUnit",["type"]="boolean",["label"]="is Unit",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="inParty",["api"]="UnitInParty",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="inParty",["type"]="boolean",["label"]="in Party",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="inRaid",["api"]="UnitInRaid",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="inRaid",["type"]="integer",["label"]="in Raid",["index"]=1,["nativeType"]="luaIndex"}}}
C.entries[#C.entries+1]={["id"]="inAnyGroup",["api"]="UnitInAnyGroup",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="inAnyGroup",["type"]="boolean",["label"]="in Any Group",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="playerOrPetInParty",["api"]="UnitPlayerOrPetInParty",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="playerOrPetInParty",["type"]="boolean",["label"]="player Or Pet In Party",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="playerOrPetInRaid",["api"]="UnitPlayerOrPetInRaid",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="playerOrPetInRaid",["type"]="boolean",["label"]="player Or Pet In Raid",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="groupRolesAssigned",["api"]="UnitGroupRolesAssigned",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="groupRolesAssigned",["type"]="string",["label"]="group Roles Assigned",["index"]=1,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="isGroupLeader",["api"]="UnitIsGroupLeader",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="isGroupLeader",["type"]="boolean",["label"]="is Group Leader",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isGroupAssistant",["api"]="UnitIsGroupAssistant",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isGroupAssistant",["type"]="boolean",["label"]="is Group Assistant",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="factionGroup",["api"]="UnitFactionGroup",["family"]="unit",["args"]={"$unit",false},["outputs"]={{["key"]="factionGroup_factionGroupTag",["type"]="string",["label"]="faction Group / faction Group Tag",["index"]=1,["nativeType"]="cstring"},{["key"]="factionGroup_localized",["type"]="string",["label"]="faction Group / localized",["index"]=2,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="isPVP",["api"]="UnitIsPVP",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isPVP",["type"]="boolean",["label"]="is P V P",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isPVPFreeForAll",["api"]="UnitIsPVPFreeForAll",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isPVPFreeForAll",["type"]="boolean",["label"]="is P V P Free For All",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isPVPSanctuary",["api"]="UnitIsPVPSanctuary",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isPVPSanctuary",["type"]="boolean",["label"]="is P V P Sanctuary",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="pvpClassification",["api"]="UnitPvpClassification",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="pvpClassification",["type"]="integer",["label"]="pvp Classification",["index"]=1,["nativeType"]="PvPUnitClassification"}}}
C.entries[#C.entries+1]={["id"]="exists",["api"]="UnitExists",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="exists",["type"]="boolean",["label"]="exists",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isVisible",["api"]="UnitIsVisible",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isVisible",["type"]="boolean",["label"]="is Visible",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isConnected",["api"]="UnitIsConnected",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isConnected",["type"]="boolean",["label"]="is Connected",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isDead",["api"]="UnitIsDead",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isDead",["type"]="boolean",["label"]="is Dead",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isGhost",["api"]="UnitIsGhost",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isGhost",["type"]="boolean",["label"]="is Ghost",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isDeadOrGhost",["api"]="UnitIsDeadOrGhost",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isDeadOrGhost",["type"]="boolean",["label"]="is Dead Or Ghost",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isUnconscious",["api"]="UnitIsUnconscious",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isUnconscious",["type"]="boolean",["label"]="is Unconscious",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="affectingCombat",["api"]="UnitAffectingCombat",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="combat",["type"]="boolean",["label"]="combat",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isAFK",["api"]="UnitIsAFK",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isAFK",["type"]="boolean",["label"]="is A F K",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isDND",["api"]="UnitIsDND",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isDND",["type"]="boolean",["label"]="is D N D",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isCharmed",["api"]="UnitIsCharmed",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isCharmed",["type"]="boolean",["label"]="is Charmed",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isPossessed",["api"]="UnitIsPossessed",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isPossessed",["type"]="boolean",["label"]="is Possessed",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isTapDenied",["api"]="UnitIsTapDenied",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isTapDenied",["type"]="boolean",["label"]="is Tap Denied",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isInteractable",["api"]="UnitIsInteractable",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isInteractable",["type"]="boolean",["label"]="is Interactable",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isGameObject",["api"]="UnitIsGameObject",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="isGameObject",["type"]="boolean",["label"]="is Game Object",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="phaseReason",["api"]="UnitPhaseReason",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="phaseReason",["type"]="integer",["label"]="phase Reason",["index"]=1,["nativeType"]="PhaseReason"}}}
C.entries[#C.entries+1]={["id"]="nameplateShowsWidgetsOnly",["api"]="UnitNameplateShowsWidgetsOnly",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="nameplateShowsWidgetsOnly",["type"]="boolean",["label"]="nameplate Shows Widgets Only",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="shouldDisplayName",["api"]="UnitShouldDisplayName",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="shouldDisplayName",["type"]="boolean",["label"]="should Display Name",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="treatAsPlayerForDisplay",["api"]="UnitTreatAsPlayerForDisplay",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="treatAsPlayerForDisplay",["type"]="boolean",["label"]="treat As Player For Display",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="threatSituation",["api"]="UnitThreatSituation",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="threatSituation",["type"]="float",["label"]="threat Situation",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="detailedThreatSituation",["api"]="UnitDetailedThreatSituation",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="detailedThreatSituation_isTanking",["type"]="boolean",["label"]="detailed Threat Situation / is Tanking",["index"]=1,["nativeType"]="bool"},{["key"]="detailedThreatSituation_status",["type"]="float",["label"]="detailed Threat Situation / status",["index"]=2,["nativeType"]="number"},{["key"]="detailedThreatSituation_scaledPercentage",["type"]="float",["label"]="detailed Threat Situation / scaled Percentage",["index"]=3,["nativeType"]="number"},{["key"]="detailedThreatSituation_rawPercentage",["type"]="float",["label"]="detailed Threat Situation / raw Percentage",["index"]=4,["nativeType"]="number"},{["key"]="detailedThreatSituation_rawThreat",["type"]="float",["label"]="detailed Threat Situation / raw Threat",["index"]=5,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="threatLeadSituation",["api"]="UnitThreatLeadSituation",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="threatLeadSituation",["type"]="float",["label"]="threat Lead Situation",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="threatPercentageOfLead",["api"]="UnitThreatPercentageOfLead",["family"]="unit",["args"]={"$player","$unit"},["outputs"]={{["key"]="threatPercentageOfLead",["type"]="float",["label"]="threat Percentage Of Lead",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="armor",["api"]="UnitArmor",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="armor_base",["type"]="float",["label"]="armor / base",["index"]=1,["nativeType"]="number"},{["key"]="armor_effective",["type"]="float",["label"]="armor / effective",["index"]=2,["nativeType"]="number"},{["key"]="armor_real",["type"]="float",["label"]="armor / real",["index"]=3,["nativeType"]="number"},{["key"]="armor_bonus",["type"]="float",["label"]="armor / bonus",["index"]=4,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="stat",["api"]="UnitStat",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="stat_currentStat",["type"]="float",["label"]="stat / current Stat",["index"]=1,["nativeType"]="number"},{["key"]="stat_effectiveStat",["type"]="float",["label"]="stat / effective Stat",["index"]=2,["nativeType"]="number"},{["key"]="stat_statPositiveBuff",["type"]="float",["label"]="stat / stat Positive Buff",["index"]=3,["nativeType"]="number"},{["key"]="stat_statNegativeBuff",["type"]="float",["label"]="stat / stat Negative Buff",["index"]=4,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="attackPower",["api"]="UnitAttackPower",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="attackPower_attackPower",["type"]="float",["label"]="attack Power / attack Power",["index"]=1,["nativeType"]="number"},{["key"]="attackPower_posBuff",["type"]="float",["label"]="attack Power / pos Buff",["index"]=2,["nativeType"]="number"},{["key"]="attackPower_negBuff",["type"]="float",["label"]="attack Power / neg Buff",["index"]=3,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="attackSpeed",["api"]="UnitAttackSpeed",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="attackSpeed_attackSpeed",["type"]="float",["label"]="attack Speed / attack Speed",["index"]=1,["nativeType"]="number"},{["key"]="attackSpeed_offhandAttackSpeed",["type"]="float",["label"]="attack Speed / offhand Attack Speed",["index"]=2,["nativeType"]="number"},{["key"]="attackSpeed_rangedAttackSpeed",["type"]="float",["label"]="attack Speed / ranged Attack Speed",["index"]=3,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="damage",["api"]="UnitDamage",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="damage_minDamage",["type"]="float",["label"]="damage / min Damage",["index"]=1,["nativeType"]="number"},{["key"]="damage_maxDamage",["type"]="float",["label"]="damage / max Damage",["index"]=2,["nativeType"]="number"},{["key"]="damage_offhandMinDamage",["type"]="float",["label"]="damage / offhand Min Damage",["index"]=3,["nativeType"]="number"},{["key"]="damage_offhandMaxDamage",["type"]="float",["label"]="damage / offhand Max Damage",["index"]=4,["nativeType"]="number"},{["key"]="damage_posBuff",["type"]="float",["label"]="damage / pos Buff",["index"]=5,["nativeType"]="number"},{["key"]="damage_negBuff",["type"]="float",["label"]="damage / neg Buff",["index"]=6,["nativeType"]="number"},{["key"]="damage_percent",["type"]="float",["label"]="damage / percent",["index"]=7,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="rangedAttackPower",["api"]="UnitRangedAttackPower",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="rangedAttackPower_attackPower",["type"]="float",["label"]="ranged Attack Power / attack Power",["index"]=1,["nativeType"]="number"},{["key"]="rangedAttackPower_posBuff",["type"]="float",["label"]="ranged Attack Power / pos Buff",["index"]=2,["nativeType"]="number"},{["key"]="rangedAttackPower_negBuff",["type"]="float",["label"]="ranged Attack Power / neg Buff",["index"]=3,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="rangedDamage",["api"]="UnitRangedDamage",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="rangedDamage_speed",["type"]="float",["label"]="ranged Damage / speed",["index"]=1,["nativeType"]="number"},{["key"]="rangedDamage_minDamage",["type"]="float",["label"]="ranged Damage / min Damage",["index"]=2,["nativeType"]="number"},{["key"]="rangedDamage_maxDamage",["type"]="float",["label"]="ranged Damage / max Damage",["index"]=3,["nativeType"]="number"},{["key"]="rangedDamage_posBuff",["type"]="float",["label"]="ranged Damage / pos Buff",["index"]=4,["nativeType"]="number"},{["key"]="rangedDamage_negBuff",["type"]="float",["label"]="ranged Damage / neg Buff",["index"]=5,["nativeType"]="number"},{["key"]="rangedDamage_percent",["type"]="float",["label"]="ranged Damage / percent",["index"]=6,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="resistance",["api"]="UnitResistance",["family"]="unit",["args"]={"$unit","$damage:Physical"},["outputs"]={{["key"]="resistance_baseResistance",["type"]="float",["label"]="resistance / base Resistance",["index"]=1,["nativeType"]="number"},{["key"]="resistance_realResistance",["type"]="float",["label"]="resistance / real Resistance",["index"]=2,["nativeType"]="number"},{["key"]="resistance_effectiveResistance",["type"]="float",["label"]="resistance / effective Resistance",["index"]=3,["nativeType"]="number"},{["key"]="resistance_bonusResistance",["type"]="float",["label"]="resistance / bonus Resistance",["index"]=4,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="castingInfo",["api"]="UnitCastingInfo",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="castingInfo_name",["type"]="string",["label"]="casting Info / name",["index"]=1,["nativeType"]="cstring"},{["key"]="castingInfo_displayName",["type"]="string",["label"]="casting Info / display Name",["index"]=2,["nativeType"]="string"},{["key"]="castingInfo_textureID",["type"]="integer",["label"]="casting Info / texture I D",["index"]=3,["nativeType"]="fileID"},{["key"]="castingInfo_startTimeMs",["type"]="float",["label"]="casting Info / start Time Ms",["index"]=4,["nativeType"]="number"},{["key"]="castingInfo_endTimeMs",["type"]="float",["label"]="casting Info / end Time Ms",["index"]=5,["nativeType"]="number"},{["key"]="castingInfo_isTradeskill",["type"]="boolean",["label"]="casting Info / is Tradeskill",["index"]=6,["nativeType"]="bool"},{["key"]="castingInfo_castID",["type"]="string",["label"]="casting Info / cast I D",["index"]=7,["nativeType"]="WOWGUID"},{["key"]="castingInfo_notInterruptible",["type"]="boolean",["label"]="casting Info / not Interruptible",["index"]=8,["nativeType"]="bool"},{["key"]="castingInfo_castingSpellID",["type"]="float",["label"]="casting Info / casting Spell I D",["index"]=9,["nativeType"]="number"},{["key"]="castingInfo_castBarID",["type"]="integer",["label"]="casting Info / cast Bar I D",["index"]=10,["nativeType"]="UnitCastBarID"},{["key"]="castingInfo_delayTimeMs",["type"]="float",["label"]="casting Info / delay Time Ms",["index"]=11,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="channelInfo",["api"]="UnitChannelInfo",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="channelInfo_name",["type"]="string",["label"]="channel Info / name",["index"]=1,["nativeType"]="cstring"},{["key"]="channelInfo_displayName",["type"]="string",["label"]="channel Info / display Name",["index"]=2,["nativeType"]="cstring"},{["key"]="channelInfo_textureID",["type"]="integer",["label"]="channel Info / texture I D",["index"]=3,["nativeType"]="fileID"},{["key"]="channelInfo_startTimeMs",["type"]="float",["label"]="channel Info / start Time Ms",["index"]=4,["nativeType"]="number"},{["key"]="channelInfo_endTimeMs",["type"]="float",["label"]="channel Info / end Time Ms",["index"]=5,["nativeType"]="number"},{["key"]="channelInfo_isTradeskill",["type"]="boolean",["label"]="channel Info / is Tradeskill",["index"]=6,["nativeType"]="bool"},{["key"]="channelInfo_notInterruptible",["type"]="boolean",["label"]="channel Info / not Interruptible",["index"]=7,["nativeType"]="bool"},{["key"]="channelInfo_spellID",["type"]="float",["label"]="channel Info / spell I D",["index"]=8,["nativeType"]="number"},{["key"]="channelInfo_isEmpowered",["type"]="boolean",["label"]="channel Info / is Empowered",["index"]=9,["nativeType"]="bool"},{["key"]="channelInfo_numEmpowerStages",["type"]="float",["label"]="channel Info / num Empower Stages",["index"]=10,["nativeType"]="number"},{["key"]="channelInfo_castBarID",["type"]="integer",["label"]="channel Info / cast Bar I D",["index"]=11,["nativeType"]="UnitCastBarID"}}}
C.entries[#C.entries+1]={["id"]="castingDuration",["api"]="UnitCastingDuration",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="castingDuration",["type"]="duration",["label"]="casting Duration",["index"]=1,["nativeType"]="LuaDurationObject"}}}
C.entries[#C.entries+1]={["id"]="channelDuration",["api"]="UnitChannelDuration",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="channelDuration",["type"]="duration",["label"]="channel Duration",["index"]=1,["nativeType"]="LuaDurationObject"}}}
C.entries[#C.entries+1]={["id"]="empoweredChannelDuration",["api"]="UnitEmpoweredChannelDuration",["family"]="unit",["args"]={"$unit",false},["outputs"]={{["key"]="empoweredChannelDuration",["type"]="duration",["label"]="empowered Channel Duration",["index"]=1,["nativeType"]="LuaDurationObject"}}}
C.entries[#C.entries+1]={["id"]="spellTargetClass",["api"]="UnitSpellTargetClass",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="spellTargetClass",["type"]="string",["label"]="spell Target Class",["index"]=1,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="spellTargetName",["api"]="UnitSpellTargetName",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="spellTargetName",["type"]="string",["label"]="spell Target Name",["index"]=1,["nativeType"]="cstring"}}}
C.entries[#C.entries+1]={["id"]="position",["api"]="UnitPosition",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="position_positionX",["type"]="float",["label"]="position / position X",["index"]=1,["nativeType"]="number"},{["key"]="position_positionY",["type"]="float",["label"]="position / position Y",["index"]=2,["nativeType"]="number"},{["key"]="position_positionZ",["type"]="float",["label"]="position / position Z",["index"]=3,["nativeType"]="number"},{["key"]="position_mapID",["type"]="float",["label"]="position / map I D",["index"]=4,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="distanceSquared",["api"]="UnitDistanceSquared",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="distanceSquared_distance",["type"]="float",["label"]="distance Squared / distance",["index"]=1,["nativeType"]="number"},{["key"]="distanceSquared_checkedDistance",["type"]="boolean",["label"]="distance Squared / checked Distance",["index"]=2,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="inRange",["api"]="UnitInRange",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="inRange_inRange",["type"]="boolean",["label"]="in Range / in Range",["index"]=1,["nativeType"]="bool"},{["key"]="inRange_checkedRange",["type"]="boolean",["label"]="in Range / checked Range",["index"]=2,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="getUnitSpeed",["api"]="GetUnitSpeed",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="getUnitSpeed_currentSpeed",["type"]="float",["label"]="get Unit Speed / current Speed",["index"]=1,["nativeType"]="number"},{["key"]="getUnitSpeed_runSpeed",["type"]="float",["label"]="get Unit Speed / run Speed",["index"]=2,["nativeType"]="number"},{["key"]="getUnitSpeed_flightSpeed",["type"]="float",["label"]="get Unit Speed / flight Speed",["index"]=3,["nativeType"]="number"},{["key"]="getUnitSpeed_swimSpeed",["type"]="float",["label"]="get Unit Speed / swim Speed",["index"]=4,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getActiveLossOfControlDataByUnit",["api"]="C_LossOfControl.GetActiveLossOfControlDataByUnit",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="getActiveLossOfControlDataByUnit",["type"]="data",["label"]="get Active Loss Of Control Data By Unit",["index"]=1,["nativeType"]="LossOfControlData",["schema"]="control"}}}
C.entries[#C.entries+1]={["id"]="getActiveLossOfControlDataCountByUnit",["api"]="C_LossOfControl.GetActiveLossOfControlDataCountByUnit",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="getActiveLossOfControlDataCountByUnit",["type"]="float",["label"]="get Active Loss Of Control Data Count By Unit",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getActiveLossOfControlDuration",["api"]="C_LossOfControl.GetActiveLossOfControlDuration",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="getActiveLossOfControlDuration",["type"]="duration",["label"]="get Active Loss Of Control Duration",["index"]=1,["nativeType"]="LuaDurationObject"}}}
C.entries[#C.entries+1]={["id"]="getAuraDataByIndex",["api"]="C_UnitAuras.GetAuraDataByIndex",["family"]="unit",["args"]={"$unit",1,"HELPFUL"},["outputs"]={{["key"]="getAuraDataByIndex",["type"]="data",["label"]="get Aura Data By Index",["index"]=1,["nativeType"]="AuraData",["schema"]="aura"}}}
C.entries[#C.entries+1]={["id"]="getAuraDataBySlot",["api"]="C_UnitAuras.GetAuraDataBySlot",["family"]="unit",["args"]={"$unit","$auraID"},["outputs"]={{["key"]="getAuraDataBySlot",["type"]="data",["label"]="get Aura Data By Slot",["index"]=1,["nativeType"]="AuraData",["schema"]="aura"}}}
C.entries[#C.entries+1]={["id"]="getAuraDataByAuraInstanceID",["api"]="C_UnitAuras.GetAuraDataByAuraInstanceID",["family"]="unit",["args"]={"$unit","$auraID"},["outputs"]={{["key"]="getAuraDataByAuraInstanceID",["type"]="data",["label"]="get Aura Data By Aura Instance I D",["index"]=1,["nativeType"]="AuraData",["schema"]="aura"}}}
C.entries[#C.entries+1]={["id"]="getAuraSlots",["api"]="C_UnitAuras.GetAuraSlots",["family"]="unit",["args"]={"$unit","HELPFUL",40},["outputs"]={{["key"]="getAuraSlots_outContinuationToken",["type"]="float",["label"]="get Aura Slots / out Continuation Token",["index"]=1,["nativeType"]="number"},{["key"]="getAuraSlots_slots",["type"]="float",["label"]="get Aura Slots / slots",["index"]=2,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getUnitAuraInstanceIDs",["api"]="C_UnitAuras.GetUnitAuraInstanceIDs",["family"]="unit",["args"]={"$unit","HELPFUL",40},["outputs"]={{["key"]="getUnitAuraInstanceIDs",["type"]="data",["label"]="get Unit Aura Instance I Ds",["index"]=1,["nativeType"]="table",["schema"]="numbers"}}}
C.entries[#C.entries+1]={["id"]="getUnitAuras",["api"]="C_UnitAuras.GetUnitAuras",["family"]="unit",["args"]={"$unit","HELPFUL",40},["outputs"]={{["key"]="buffs",["type"]="data",["label"]="get Unit Auras",["index"]=1,["nativeType"]="table",["schema"]="auras"}}}
C.entries[#C.entries+1]={["id"]="getUnitAuraBySpellID",["api"]="C_UnitAuras.GetUnitAuraBySpellID",["family"]="unit",["args"]={"$unit","$option:spellID"},["outputs"]={{["key"]="getUnitAuraBySpellID",["type"]="data",["label"]="get Unit Aura By Spell I D",["index"]=1,["nativeType"]="AuraData",["schema"]="aura"}}}
C.entries[#C.entries+1]={["id"]="getAuraDataBySpellName",["api"]="C_UnitAuras.GetAuraDataBySpellName",["family"]="unit",["args"]={"$unit","$option:spellName"},["outputs"]={{["key"]="getAuraDataBySpellName",["type"]="data",["label"]="get Aura Data By Spell Name",["index"]=1,["nativeType"]="AuraData",["schema"]="aura"}}}
C.entries[#C.entries+1]={["id"]="getAuraDuration",["api"]="C_UnitAuras.GetAuraDuration",["family"]="unit",["args"]={"$unit","$auraID"},["outputs"]={{["key"]="getAuraDuration",["type"]="duration",["label"]="get Aura Duration",["index"]=1,["nativeType"]="LuaDurationObject"}}}
C.entries[#C.entries+1]={["id"]="getAuraApplicationDisplayCount",["api"]="C_UnitAuras.GetAuraApplicationDisplayCount",["family"]="unit",["args"]={"$unit","$auraID",2,99},["outputs"]={{["key"]="getAuraApplicationDisplayCount",["type"]="string",["label"]="get Aura Application Display Count",["index"]=1,["nativeType"]="string"}}}
C.entries[#C.entries+1]={["id"]="getAuraDispelTypeColor",["api"]="C_UnitAuras.GetAuraDispelTypeColor",["family"]="unit",["args"]={"$unit","$auraID","$neutralColorCurve"},["outputs"]={{["key"]="getAuraDispelTypeColor",["type"]="data",["label"]="Aura color (neutral curve)",["index"]=1,["nativeType"]="colorRGBA",["schema"]="color"}}}
C.entries[#C.entries+1]={["id"]="getAuraCasterGUID",["api"]="C_UnitAuras.GetAuraCasterGUID",["family"]="unit",["args"]={"$unit","$auraID"},["outputs"]={{["key"]="getAuraCasterGUID",["type"]="string",["label"]="get Aura Caster G U I D",["index"]=1,["nativeType"]="WOWGUID"}}}
C.entries[#C.entries+1]={["id"]="getRaidTargetIndex",["api"]="GetRaidTargetIndex",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="getRaidTargetIndex",["type"]="integer",["label"]="get Raid Target Index",["index"]=1,["nativeType"]="luaIndex"}}}
C.entries[#C.entries+1]={["id"]="canBeRaidTarget",["api"]="CanBeRaidTarget",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="canBeRaidTarget",["type"]="boolean",["label"]="can Be Raid Target",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="getUnit",["api"]="C_TooltipInfo.GetUnit",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="tooltip",["type"]="data",["label"]="tooltip",["index"]=1,["nativeType"]="TooltipData",["schema"]="tooltip"}}}
C.entries[#C.entries+1]={["id"]="getUnitAura",["api"]="C_TooltipInfo.GetUnitAura",["family"]="unit",["args"]={"$unit",1,"HELPFUL"},["outputs"]={{["key"]="auraTooltip",["type"]="data",["label"]="aura Tooltip",["index"]=1,["nativeType"]="TooltipData",["schema"]="tooltip"}}}
C.entries[#C.entries+1]={["id"]="getBestMapForUnit",["api"]="C_Map.GetBestMapForUnit",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="bestMapID",["type"]="float",["label"]="best Map I D",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="getPlayerMapPosition",["api"]="C_Map.GetPlayerMapPosition",["family"]="unit",["args"]={"$bestMap","$unit"},["outputs"]={{["key"]="mapPosition",["type"]="data",["label"]="map Position",["index"]=1,["nativeType"]="vector2",["schema"]="vector2"}}}
C.entries[#C.entries+1]={["id"]="checkInteractDistance",["api"]="CheckInteractDistance",["family"]="unit",["args"]={"$unit",1},["outputs"]={{["key"]="interactRange",["type"]="boolean",["label"]="interact Range",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="getPlayerFacing",["api"]="GetPlayerFacing",["family"]="unit",["args"]={},["outputs"]={{["key"]="playerFacing",["type"]="float",["label"]="player Facing",["index"]=1,["nativeType"]="number"}}}
C.entries[#C.entries+1]={["id"]="isSpellInRange",["api"]="C_Spell.IsSpellInRange",["family"]="unit",["args"]={"$option:spellID","$unit"},["outputs"]={{["key"]="spellRange",["type"]="boolean",["label"]="spell Range",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isTargetWithinSwingRange",["api"]="C_SwingTimer.IsTargetWithinSwingRange",["family"]="unit",["args"]={"$swing:MainHand"},["outputs"]={{["key"]="targetSwingRange",["type"]="boolean",["label"]="target Swing Range",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="isNamePlateUnitBehindCamera",["api"]="C_NamePlateManager.IsNamePlateUnitBehindCamera",["family"]="unit",["args"]={"$unit"},["outputs"]={{["key"]="behindCamera",["type"]="boolean",["label"]="behind Camera",["index"]=1,["nativeType"]="bool"}}}
C.entries[#C.entries+1]={["id"]="mounted",["api"]="IsMounted",["family"]="player",["args"]={},["playerOnly"]=true,["outputs"]={{["key"]="mounted",["type"]="boolean",["label"]="Mounted",["index"]=1}}}
C.entries[#C.entries+1]={["id"]="resting",["api"]="IsResting",["family"]="player",["args"]={},["playerOnly"]=true,["outputs"]={{["key"]="resting",["type"]="boolean",["label"]="Resting",["index"]=1}}}
C.entries[#C.entries+1]={["id"]="moving",["api"]="IsPlayerMoving",["family"]="player",["args"]={},["playerOnly"]=true,["outputs"]={{["key"]="moving",["type"]="boolean",["label"]="Moving",["index"]=1}}}
C.entries[#C.entries+1]={["id"]="mana",["api"]="UnitPower",["family"]="power",["args"]={"$unit","$power:Mana"},["outputs"]={{["key"]="mana",["type"]="float",["label"]="mana",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="manaMax",["api"]="UnitPowerMax",["family"]="power",["args"]={"$unit","$power:Mana"},["outputs"]={{["key"]="manaMax",["type"]="float",["label"]="mana Max",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="rage",["api"]="UnitPower",["family"]="power",["args"]={"$unit","$power:Rage"},["outputs"]={{["key"]="rage",["type"]="float",["label"]="rage",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="rageMax",["api"]="UnitPowerMax",["family"]="power",["args"]={"$unit","$power:Rage"},["outputs"]={{["key"]="rageMax",["type"]="float",["label"]="rage Max",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="energy",["api"]="UnitPower",["family"]="power",["args"]={"$unit","$power:Energy"},["outputs"]={{["key"]="energy",["type"]="float",["label"]="energy",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="energyMax",["api"]="UnitPowerMax",["family"]="power",["args"]={"$unit","$power:Energy"},["outputs"]={{["key"]="energyMax",["type"]="float",["label"]="energy Max",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="focus",["api"]="UnitPower",["family"]="power",["args"]={"$unit","$power:Focus"},["outputs"]={{["key"]="focus",["type"]="float",["label"]="focus",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="focusMax",["api"]="UnitPowerMax",["family"]="power",["args"]={"$unit","$power:Focus"},["outputs"]={{["key"]="focusMax",["type"]="float",["label"]="focus Max",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="comboPoints",["api"]="UnitPower",["family"]="power",["args"]={"$unit","$power:ComboPoints"},["outputs"]={{["key"]="comboPoints",["type"]="float",["label"]="combo Points",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="comboPointsMax",["api"]="UnitPowerMax",["family"]="power",["args"]={"$unit","$power:ComboPoints"},["outputs"]={{["key"]="comboPointsMax",["type"]="float",["label"]="combo Points Max",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="runicPower",["api"]="UnitPower",["family"]="power",["args"]={"$unit","$power:RunicPower"},["outputs"]={{["key"]="runicPower",["type"]="float",["label"]="runic Power",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="runicPowerMax",["api"]="UnitPowerMax",["family"]="power",["args"]={"$unit","$power:RunicPower"},["outputs"]={{["key"]="runicPowerMax",["type"]="float",["label"]="runic Power Max",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="alternatePower",["api"]="UnitPower",["family"]="power",["args"]={"$unit","$power:Alternate"},["outputs"]={{["key"]="alternatePower",["type"]="float",["label"]="alternate Power",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="alternatePowerMax",["api"]="UnitPowerMax",["family"]="power",["args"]={"$unit","$power:Alternate"},["outputs"]={{["key"]="alternatePowerMax",["type"]="float",["label"]="alternate Power Max",["index"]=1,["nonnegative"]=true}}}
C.entries[#C.entries+1]={["id"]="debuffs",["api"]="C_UnitAuras.GetUnitAuras",["family"]="unit",["args"]={"$unit","HARMFUL",40},["outputs"]={{["key"]="debuffs",["type"]="data",["label"]="Debuffs",["index"]=1,["nativeType"]="table",["schema"]="auras"}}}
C.fields={}
for _,entry in ipairs(C.entries) do for _,field in ipairs(entry.outputs) do C.fields[field.key]=field end end

-- Known-field projections, never arbitrary traversal of native objects.
C.schemas={
 aura={name="string",icon="integer",applications="integer",dispelName="string",duration="float",expirationTime="float",sourceUnit="string",isStealable="boolean",nameplateShowPersonal="boolean",spellId="integer",canApplyAura="boolean",isBossAura="boolean",isFromPlayerOrPlayerPet="boolean",nameplateShowAll="boolean",timeMod="float",isHelpful="boolean",isHarmful="boolean",auraInstanceID="integer",points="data"},
 powerBar={ID="integer",barType="integer",minPower="float",startInset="float",endInset="float",smooth="boolean",hideFromOthers="boolean",showOnRaid="boolean",opaqueSpark="boolean",opaqueFlash="boolean",anchorTop="boolean",forcePercentage="boolean",sparkUnderFrame="boolean",flashAtMinPower="boolean",fractionalCounter="boolean",animateNumbers="boolean",attachTooltipToBar="boolean"},
 control={locType="string",spellID="integer",displayText="string",iconTexture="integer",startTime="float",timeRemaining="float",duration="float",lockoutSchool="integer",priority="integer",displayType="integer",auraInstanceID="integer"},
 tooltip={type="integer",id="integer",unitToken="string",guid="string",lines="data"},
 tooltipLine={type="integer",leftText="string",rightText="string",id="integer",leftColor="data",rightColor="data"},
 vector2={x="float",y="float"},color={r="float",g="float",b="float",a="float"},
 geometry={x="float",y="float",left="float",bottom="float",width="float",height="float",scale="float",forbidden="boolean"},
 duration={remaining="float",elapsed="float",total="float",startTime="float",endTime="float",modRate="float",remainingPercent="float",elapsedPercent="float",expired="boolean",started="boolean",active="boolean",zero="boolean",hasSecretValues="boolean"},
 calculator={},numbers={value="float"},auras={},tooltipLines={},controls={}
}
C.nestedSchemas={aura={points="numbers"},tooltip={lines="tooltipLines"},tooltipLine={leftColor="color",rightColor="color"}}
C.schemas.auras=C.schemas.aura;C.schemas.tooltipLines=C.schemas.tooltipLine;C.schemas.controls=C.schemas.control
C.methods={duration={remaining="GetRemainingDuration",elapsed="GetElapsedDuration",total="GetTotalDuration",startTime="GetStartTime",endTime="GetEndTime",modRate="GetModRate",remainingPercent="GetRemainingPercent",elapsedPercent="GetElapsedPercent",expired="HasExpired",started="HasStarted",active="IsActive",zero="IsZero",hasSecretValues="HasSecretValues"},calculator={}}
C.entries[#C.entries+1]={id="nameplateGeometry",api="C_NamePlate.GetNamePlateForUnit",family="geometry",args={"$unit",false},nameplateOnly=true,outputs={{key="nameplateGeometry",type="data",schema="geometry",label="Nameplate geometry",index=1}}}
C.fields.nameplateGeometry=C.entries[#C.entries].outputs[1]
C.schemas.calculator["currentHealth"]="float";C.methods.calculator["currentHealth"]={name="GetCurrentHealth",index=1}
C.schemas.calculator["currentHealthPercent"]="float";C.methods.calculator["currentHealthPercent"]={name="GetCurrentHealthPercent",index=1}
C.schemas.calculator["damageAbsorbClampMode"]="float";C.methods.calculator["damageAbsorbClampMode"]={name="GetDamageAbsorbClampMode",index=1}
C.schemas.calculator["damageAbsorbs"]="float";C.methods.calculator["damageAbsorbs"]={name="GetDamageAbsorbs",index=1}
C.schemas.calculator["damageAbsorbs_clamped"]="boolean";C.methods.calculator["damageAbsorbs_clamped"]={name="GetDamageAbsorbs",index=2}
C.schemas.calculator["healAbsorbClampMode"]="float";C.methods.calculator["healAbsorbClampMode"]={name="GetHealAbsorbClampMode",index=1}
C.schemas.calculator["healAbsorbMode"]="float";C.methods.calculator["healAbsorbMode"]={name="GetHealAbsorbMode",index=1}
C.schemas.calculator["healAbsorbs"]="float";C.methods.calculator["healAbsorbs"]={name="GetHealAbsorbs",index=1}
C.schemas.calculator["healAbsorbs_clamped"]="boolean";C.methods.calculator["healAbsorbs_clamped"]={name="GetHealAbsorbs",index=2}
C.schemas.calculator["incomingHealClampMode"]="float";C.methods.calculator["incomingHealClampMode"]={name="GetIncomingHealClampMode",index=1}
C.schemas.calculator["incomingHealOverflowPercent"]="float";C.methods.calculator["incomingHealOverflowPercent"]={name="GetIncomingHealOverflowPercent",index=1}
C.schemas.calculator["incomingHeals"]="float";C.methods.calculator["incomingHeals"]={name="GetIncomingHeals",index=1}
C.schemas.calculator["incomingHeals_amountFromHealer"]="float";C.methods.calculator["incomingHeals_amountFromHealer"]={name="GetIncomingHeals",index=2}
C.schemas.calculator["incomingHeals_amountFromOthers"]="float";C.methods.calculator["incomingHeals_amountFromOthers"]={name="GetIncomingHeals",index=3}
C.schemas.calculator["incomingHeals_clamped"]="boolean";C.methods.calculator["incomingHeals_clamped"]={name="GetIncomingHeals",index=4}
C.schemas.calculator["maximumDamageAbsorbs"]="float";C.methods.calculator["maximumDamageAbsorbs"]={name="GetMaximumDamageAbsorbs",index=1}
C.schemas.calculator["maximumHealAbsorbs"]="float";C.methods.calculator["maximumHealAbsorbs"]={name="GetMaximumHealAbsorbs",index=1}
C.schemas.calculator["maximumHealth"]="float";C.methods.calculator["maximumHealth"]={name="GetMaximumHealth",index=1}
C.schemas.calculator["maximumHealthMode"]="float";C.methods.calculator["maximumHealthMode"]={name="GetMaximumHealthMode",index=1}
C.schemas.calculator["maximumIncomingHeals"]="float";C.methods.calculator["maximumIncomingHeals"]={name="GetMaximumIncomingHeals",index=1}
C.schemas.calculator["missingHealth"]="float";C.methods.calculator["missingHealth"]={name="GetMissingHealth",index=1}
C.schemas.calculator["missingHealthPercent"]="float";C.methods.calculator["missingHealthPercent"]={name="GetMissingHealthPercent",index=1}
-- UnitHealPredictionValues: fixed fields from the pinned shared API schema.
for _,field in ipairs({"health","healthMax","totalIncomingHeals","totalIncomingHealsFromHealer","totalDamageAbsorbs","totalHealAbsorbs"}) do
 local key="predictedValues_"..field
 C.schemas.calculator[key]="float";C.methods.calculator[key]={name="GetPredictedValues",index=1,path=field}
end
C.schemas.calculator["totalDamageAbsorbs"]="float";C.methods.calculator["totalDamageAbsorbs"]={name="GetTotalDamageAbsorbs",index=1}
C.schemas.calculator["totalHealAbsorbs"]="float";C.methods.calculator["totalHealAbsorbs"]={name="GetTotalHealAbsorbs",index=1}
C.schemas.calculator["totalIncomingHeals"]="float";C.methods.calculator["totalIncomingHeals"]={name="GetTotalIncomingHeals",index=1}
C.schemas.calculator["totalIncomingHealsFromHealer"]="float";C.methods.calculator["totalIncomingHealsFromHealer"]={name="GetTotalIncomingHealsFromHealer",index=1}
C.schemas.calculator["hasSecretValues"]="boolean";C.methods.calculator["hasSecretValues"]={name="HasSecretValues",index=1}

for _,entry in ipairs(C.entries) do
 if entry.api=="UnitPowerType" then entry.args={"$unit",0} end
 if entry.api=="UnitInParty" or entry.api=="UnitInRaid" or entry.api=="UnitInAnyGroup" or entry.api=="UnitIsPlayer" or entry.api=="UnitIsHumanPlayer" or entry.api=="UnitPlayerOrPetInParty" or entry.api=="UnitPlayerOrPetInRaid" then entry.args={"$unit","$nil"} end
 if entry.api=="GetPlayerFacing" then entry.playerOnly=true end
 if entry.api=="C_SwingTimer.IsTargetWithinSwingRange" then entry.targetOnly=true end
 if entry.api=="C_UnitAuras.GetAuraDataBySlot" then entry.args={"$unit","$auraSlot"} end
 if entry.api=="C_UnitAuras.GetAuraSlots" then entry.outputs[2].type="data";entry.outputs[2].schema="numbers";entry.outputs[2].variadic=true end
end

for _,entry in ipairs(C.entries) do
 if entry.api=="UnitPowerBarTimerInfo" then entry.args={"$unit",0} end
 if entry.api=="UnitIsGroupLeader" then entry.args={"$unit","$nil"} end
end

C.queryDefaults={spellName="",damageClass=0,spellID=0,auraIndex=1,controlIndex=1,statIndex=1,interactionIndex=1}
for _,entry in ipairs(C.entries) do
 if entry.api=="C_UnitAuras.GetAuraDataByIndex" or entry.api=="C_TooltipInfo.GetUnitAura" then entry.args[2]="$option:auraIndex" end
 if entry.api=="C_LossOfControl.GetActiveLossOfControlDataByUnit" or entry.api=="C_LossOfControl.GetActiveLossOfControlDuration" then entry.args[2]="$option:controlIndex" end
 if entry.api=="UnitStat" then entry.args[2]="$option:statIndex" end
 if entry.api=="CheckInteractDistance" then entry.args[2]="$option:interactionIndex" end
end
C.dynamic={}
for _,entry in ipairs(C.entries) do
 if entry.id=="position" or entry.id=="distanceSquared" or entry.id=="inRange" or entry.id=="getUnitSpeed" or entry.id=="checkInteractDistance" or entry.api=="C_Spell.IsSpellInRange" or entry.api=="GetPlayerFacing" or entry.api=="C_SwingTimer.IsTargetWithinSwingRange" or entry.id=="nameplateGeometry" or entry.api=="C_NamePlateManager.IsNamePlateUnitBehindCamera" then
    for _,field in ipairs(entry.outputs) do C.dynamic[field.key]=true end
 end
end

for _,entry in ipairs(C.entries) do
 for _,field in ipairs(entry.outputs) do if field.type=="duration" then C.dynamic[field.key]=true end end
end

for _,entry in ipairs(C.entries) do
 if entry.api=="UnitResistance" then entry.args={"$unit","$option:damageClass"} end
end
